project_id = "vpuzzcerqxqinouqjodq"

[auth]
enabled = true

[functions.edit-text]
verify_jwt = false

[functions.proxy-model]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true
